trigger:
- main

variables:
  - name: env
    value: "scora"
  - name: score_user
    value: "azureuser"
  - name: server
    value: "gl05b"

steps:
  - bash: 
      echo $(env) $(score_user) $(server)
  - task: CmdLine@2
    displayName: SSH to ${{ variables.server }}
    inputs:
      script: |
        ssh -i az-nr-linux-vm-keypair-ssh.pem azureuser@52.174.68.176
  - task: CmdLine@2
    displayName: Copying the files
    inputs:
      script: |
        scp -r -o StrictHostKeyChecking=no ./citman
