create table LOV_COUNTRY
(
  iso3                      varchar2(3 char),
  name                      varchar2(200 char),
  iso2                      varchar2(2 char),
  nat_mandatory             varchar2(1 char)
)
tablespace DATA;

grant ALL on LOV_COUNTRY to PUBLIC;

begin
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('NGA','NIGERIA','NG','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('NIU','NIOUE','NU','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('NFK','NORFOLK, ILE','NF','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('NOR','NORVEGE','NO','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('NCL','NOUVELLE CALEDONIE','NC','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('NER','NIGER','NE','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('NZL','NOUVELLE ZELANDE','NZ','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('IOT','OCEAN INDIEN TERRIT.BRITANNI.','IO','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('OMN','OMAN','OM','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('UGA','OUGANDA','UG','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('UZB','OUZBEKISTAN','UZ','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('PUS','PACIFIQUE, DIVERSES ILES DU','PU','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('PCI','PACIFIQUE, ILES DU','PC','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('PAK','PAKISTAN','PK','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('PLW','PALAU','PW','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('PAN','PANAMA','PA','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('PNG','PAPOUASIE-NOUVELLE-GUINEE','PG','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('PRY','PARAGUAY','PY','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('NLD','PAYS-BAS','NL','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('PER','PEROU','PE','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('PHL','PHILIPPINES','PH','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('PCN','PITCAIRN','PN','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('POL','POLOGNE','PL','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('PYF','POLYNESIE FRANCAISE','PF','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('PRI','PORTO RICO','PR','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('PRT','PORTUGAL','PT','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('QAT','QATAR','QA','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('CZE','REP.TCHEQUE','CZ','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('COD','REPUBLIQUE DEMOCRATIQUE CONGO','CD','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('FJI','REPUBLIQUE DES FIDJI','FJ','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('ROM','ROUMANIE','RO','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('GBR','ROYAUME-UNI','GB','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('RWA','RWANDA','RW','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('ESH','SAHARA OCCIDENTAL','EH','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('KNA','SAINT-KITTS-ET-NEVIS','KN','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('REU','REUNION','RE','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('SMR','SAINT-MARIN','SM','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('SPM','SAINT-PIERRE-ET-MIQUELON','PM','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('VCT','SAINT-VINCENT-ET-GRENADINES','VC','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('SHN','SAINTE-HELENE','SH','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('LCA','SAINTE-LUCIE','LC','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('SLB','SALOMON, ILES','SB','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('WSM','SAMOA','WS','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('ASM','SAMOA AMERICAINES','AS','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('STP','SAO TOME-ET-PRINCIPE','ST','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('SEN','SENEGAL','SN','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('SRB','SERBIE','RS','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('SYC','SEYCHELLES','SC','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('SLE','SIERRA LEONE','SL','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('SGP','SINGAPOUR','SG','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('SVK','SLOVAQUIE','SK','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('SVN','SLOVENIE','SI','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('SOM','SOMALIE','SO','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('SDN','SOUDAN','SD','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('SGS','SOUTH GEORGIA AND SANDWICH','GS','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('YMD','SOUTH YEMEN','YD','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('LKA','SRI-LANKA','LK','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('SWE','SUEDE','SE','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('CHE','SUISSE','CH','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('SUR','SURINAME','SR','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('SWZ','SWAZILAND','SZ','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('SYR','SYRIE','SY','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('TJK','TADJIKISTAN','TJ','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('SJM','SVALBARD ET ILE JAN MAYEN','SJ','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('TWN','TAIWAN','TW','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('TZA','TANZANIE','TZ','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('TCD','TCHAD','TD','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('ATN','TERRE DE LA REINE MAUD','NQ','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('ATF','TERRES AUSTRALES FRANCAISES','TF','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('PSE','TERRITOIRE PALESTINIEN','PS','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('THA','THAILANDE','TH','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('TMP','TIMOR ORIENTAL','TL','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('TGO','TOGO','TG','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('TKL','TOKELAOU','TK','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('TON','TONGA','TO','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('TTO','TRINITE-ET-TOBAGO','TT','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('TUN','TUNISIE','TN','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('TKM','TURKMENISTAN','TM','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('TUR','TURQUIE','TR','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('TUV','TUVALU','TV','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('UKR','UKRAINE','UA','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('URY','URUGUAY','UY','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('VUT','VANUATU','VU','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('VEN','VENEZUELA','VE','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('VNM','VIETNAM','VN','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('WAK','WAKE, ILE DE','FM','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('WLF','WALLIS ET FUTUNA, ILES','WF','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('YEM','YEMEN','YE','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('VAT','VATICAN','VA','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('ZMB','ZAMBIE','ZM','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('ZWE','ZIMBABWE','ZW','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('AFG','AFGHANISTAN','AF','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('ZAF','AFRIQUE DU SUD','ZA','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('ALB','ALBANIE','AL','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('DZA','ALGERIE','DZ','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('DEU','ALLEMAGNE','DE','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('AGO','ANGOLA','AO','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('AIA','ANGUILLA','AI','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('ATA','ANTARCTIQUE','AQ','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('ATG','ANTIGUA-ET-BARBUDA','AG','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('ANT','ANTILLES NEERLANDAISES','AN','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('AND','ANDORRE','AD','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('SAU','ARABIE SAOUDITE','SA','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('ARG','ARGENTINE','AR','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('ARM','ARMENIE','AM','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('ABW','ARUBA','AW','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('AUS','AUSTRALIE','AU','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('AUT','AUTRICHE','AT','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('AZE','AZERBAIJAN','AZ','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('BHS','BAHAMAS','BS','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('BHR','BAHREIN','BH','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('BGD','BANGLADESH','BD','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('BRB','BARBADE','BB','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('BLR','BELARUS','BY','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('BEL','BELGIQUE','BE','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('BLZ','BELIZE','BZ','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('BEN','BENIN','BJ','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('BMU','BERMUDES','BM','N');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('BTN','BHOUTAN','BT','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('BUR','BIRMANIE','MM','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('BOL','BOLIVIE','BO','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('BIH','BOSNIE-HERZEGOVINE','BA','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('BWA','BOTSWANA','BW','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('BVT','BOUVET, ILE','BV','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('BRA','BRESIL','BR','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('BRN','BRUNEI DARUSSALAM','BN','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('BGR','BULGARIE','BG','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('BDI','BURUNDI','BI','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('CYM','CAIMANES, ILES','KY','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('KHM','CAMBODGE','KH','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('CMR','CAMEROUN','CM','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('CAN','CANADA','CA','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('BFA','BURKINA FASO','BF','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('CTE','CANTON ET ENDERBURY ILES','CX','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('CPV','CAP-VERT','CV','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('CAF','CENTRAFRICAINE, REPUBLIQUE','CF','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('CHL','CHILI','CL','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('CHN','CHINE','CN','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('CXR','CHRISTMAS, ILE','CX','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('CYP','CHYPRE','CY','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('CCK','COCOS (KEELING) ILES DES','CC','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('COL','COLOMBIE','CO','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('COM','COMORES','KM','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('COG','CONGO','CG','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('COK','COOK, ILES','CK','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('KOR','COREE','KR','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('PRK','COREE DEMOCRATIQUE','KP','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('CRI','COSTA RICA','CR','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('CIV','COTE D IVOIRE','CI','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('HRV','CROATIE','HR','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('CUB','CUBA','CU','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('DNK','DANEMARK','DK','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('DJI','DJIBOUTI','DJ','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('DOM','DOMINICAINE, REPUBLIQUE','DO','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('DMA','DOMINIQUE','DM','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('EGY','EGYPTE','EG','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('SLV','EL SALVADOR','SV','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('ARE','EMIRATS ARABES UNIS','AE','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('ETH','ETHIOPIE','ET','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('FLK','FALKLAND, ILES (MALVINAS)','FK','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('RUS','FEDERATION RUSSE','RU','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('FRO','FEROE, ILES','FO','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('ECU','EQUATEUR','EC','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('ERI','ERITREA','ER','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('ESP','ESPAGNE','ES','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('EST','ESTONIE','EE','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('USA','ETATS UNIS','US','');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('FIN','FINLANDE','FI','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('FRA','FRANCE','FR','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('GAB','GABON','GA','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('GMB','GAMBIE','GM','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('GEO','GEORGIE','GE','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('GHA','GHANA','GH','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('GIB','GIBRALTAR','GI','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('GRC','GRECE','GR','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('GRD','GRENADE','GD','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('GRL','GROENLAND','GL','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('GLP','GUADELOUPE','GP','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('GUM','GUAM','GU','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('GTM','GUATEMALA','GT','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('GIN','GUINEE','GN','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('GNQ','GUINEE EQUATORIALE','GQ','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('GNB','GUINEE-BISSAU','GW','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('GUY','GUYANA','GY','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('GUF','GUYANE FRANCAISE','GF','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('HTI','HAITI','HT','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('HMD','HEARD ET MC DONALD, ILES','HM','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('HKG','HONG KONG','HK','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('HUN','HONGRIE','HU','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('UMI','ILES MINEURES ELOIGNEES DE USA','UM','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('TCA','ILES TURKS ET CAIQUES','TC','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('VIR','ILES VIERGES (E-U)','VI','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('HND','HONDURAS','HN','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('VGB','ILES VIERGES BRITANNIQUES','VG','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('IND','INDE','IN','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('IDN','INDONESIE','ID','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('IRN','IRAN','IR','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('IRQ','IRAQ','IQ','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('IRL','IRLANDE','IE','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('ISL','ISLANDE','IS','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('ISR','ISRAEL','IL','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('ITA','ITALIE','IT','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('JAM','JAMAIQUE','JM','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('JPN','JAPON','JP','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('JTN','JOHNSTON, ILE','JT','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('JOR','JORDANIE','JO','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('KAZ','KAZAKHSTAN','KZ','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('KEN','KENYA','KE','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('KGZ','KIRGHIZISTAN','KG','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('KIR','KIRIBATI','KI','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('KWT','KOWEIT','KW','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('LAO','LAOS REPUB.DEMOCRAT.POPULAIRE','LA','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('LSO','LESOTHO','LS','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('LVA','LETTONIE','LV','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('LBN','LIBAN','LB','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('LBR','LIBERIA','LR','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('LBY','LIBYE','LY','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('LIE','LIECHTENSTEIN','LI','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('LUX','LUXEMBOURG','LU','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('MAC','MACAO','MO','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('MKD','MACEDONIA','MK','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('MDG','MADAGASCAR','MG','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('MYS','MALAISIE','MY','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('LTU','LITHUANIE','LT','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('MWI','MALAWI','MW','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('MDV','MALDIVES','MV','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('MLI','MALI','ML','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('MLT','MALTE','MT','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('MNP','MARIANNES DU NORD, ILES','MP','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('MAR','MAROC','MA','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('MHL','MARSHALL ILES','MH','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('MTQ','MARTINIQUE','MQ','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('MUS','MAURICE','MU','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('MRT','MAURITANIE','MR','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('MYT','MAYOTTE','YT','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('MEX','MEXIQUE','MX','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('FSM','MICRONESIE','FM','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('MID','MIDWAY, ILES','MI','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('MDA','MOLDOVA','MD','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('MCO','MONACO','MC','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('MNG','MONGOLIE','MN','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('MNE','MONTENEGRO','ME','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('MSR','MONTSERRAT','MS','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('MOZ','MOZAMBIQUE','MZ','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('MMR','MYANMAR (BURMA)','MM','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('NAM','NAMIBIE','NA','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('NRU','NAURU','NR','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('NPL','NEPAL','NP','Y');
insert into LOV_COUNTRY (iso3, name, iso2, nat_Mandatory) values('NIC','NICARAGUA','NI','Y');
commit;
end;