insert into LOV_CS_LEGAL_FORM (CS_PROVIDER_CODE, CS_DESCRIPTION, IMX_LEGAL_FORM) values (	1	,'Sole trader with one owner',	'EENM');
insert into LOV_CS_LEGAL_FORM (CS_PROVIDER_CODE, CS_DESCRIPTION, IMX_LEGAL_FORM) values (	2	,'Sole trafer with several owners',	'EENM');
insert into LOV_CS_LEGAL_FORM (CS_PROVIDER_CODE, CS_DESCRIPTION, IMX_LEGAL_FORM) values (	3	,'Public limited company or limited company being set up on A form',	'EENM');
insert into LOV_CS_LEGAL_FORM (CS_PROVIDER_CODE, CS_DESCRIPTION, IMX_LEGAL_FORM) values (	5	,'Shipping company',	'EENM');
insert into LOV_CS_LEGAL_FORM (CS_PROVIDER_CODE, CS_DESCRIPTION, IMX_LEGAL_FORM) values (	7	,'Partnership',	'EENM');
insert into LOV_CS_LEGAL_FORM (CS_PROVIDER_CODE, CS_DESCRIPTION, IMX_LEGAL_FORM) values (	11	,'General partnership (VOF)',	'VOF');
insert into LOV_CS_LEGAL_FORM (CS_PROVIDER_CODE, CS_DESCRIPTION, IMX_LEGAL_FORM) values (	12	,'Public limited company or limited company being set up on B form',	'VOF');
insert into LOV_CS_LEGAL_FORM (CS_PROVIDER_CODE, CS_DESCRIPTION, IMX_LEGAL_FORM) values (	13	,'Public partnership',	'VOF');
insert into LOV_CS_LEGAL_FORM (CS_PROVIDER_CODE, CS_DESCRIPTION, IMX_LEGAL_FORM) values (	14	,'Public partnership with corporate existence',	'VOF');
insert into LOV_CS_LEGAL_FORM (CS_PROVIDER_CODE, CS_DESCRIPTION, IMX_LEGAL_FORM) values (	21	,'Limited partnership (CV) with one managing partner',	'CV');
insert into LOV_CS_LEGAL_FORM (CS_PROVIDER_CODE, CS_DESCRIPTION, IMX_LEGAL_FORM) values (	22	,'Limited partnership (CV) with several managing partners',	'CV');
insert into LOV_CS_LEGAL_FORM (CS_PROVIDER_CODE, CS_DESCRIPTION, IMX_LEGAL_FORM) values (	23	,'public limited company or limited company being set up on D form',	'CV');
insert into LOV_CS_LEGAL_FORM (CS_PROVIDER_CODE, CS_DESCRIPTION, IMX_LEGAL_FORM) values (	24	,'Limited partnership (CV) with corporate existence',	'CV');
insert into LOV_CS_LEGAL_FORM (CS_PROVIDER_CODE, CS_DESCRIPTION, IMX_LEGAL_FORM) values (	40	,'Limited company being set up (Rechtspersoon in oprichting)',	'CV');
insert into LOV_CS_LEGAL_FORM (CS_PROVIDER_CODE, CS_DESCRIPTION, IMX_LEGAL_FORM) values (	41	,'Private limited liability company (BV) with ordinary structure',	'BV');
insert into LOV_CS_LEGAL_FORM (CS_PROVIDER_CODE, CS_DESCRIPTION, IMX_LEGAL_FORM) values (	42	,'Private limited liability company (BV) according regulations of the structural company',	'BV');
insert into LOV_CS_LEGAL_FORM (CS_PROVIDER_CODE, CS_DESCRIPTION, IMX_LEGAL_FORM) values (	51	,'Limited company (NV) with ordinary structure',	'NV');
insert into LOV_CS_LEGAL_FORM (CS_PROVIDER_CODE, CS_DESCRIPTION, IMX_LEGAL_FORM) values (	52	,'Limited company (NV) according regulations of the structural company',	'NV');
insert into LOV_CS_LEGAL_FORM (CS_PROVIDER_CODE, CS_DESCRIPTION, IMX_LEGAL_FORM) values (	53	,'NV investment company with a variable capital',	'NV');
insert into LOV_CS_LEGAL_FORM (CS_PROVIDER_CODE, CS_DESCRIPTION, IMX_LEGAL_FORM) values (	54	,'NV investment company with a variable capital, according to the regulations',	'NV');
insert into LOV_CS_LEGAL_FORM (CS_PROVIDER_CODE, CS_DESCRIPTION, IMX_LEGAL_FORM) values (	55	,'European limited company (SE) with ordinary structure',	'NV');
insert into LOV_CS_LEGAL_FORM (CS_PROVIDER_CODE, CS_DESCRIPTION, IMX_LEGAL_FORM) values (	56	,'European limited company (SE) according to the regulations of the structural company of the structural company',	'NV');
insert into LOV_CS_LEGAL_FORM (CS_PROVIDER_CODE, CS_DESCRIPTION, IMX_LEGAL_FORM) values (	61	,'Co-operative society excluded liability (Coöperatie U.A.) with ordinary structure',	'NV');
insert into LOV_CS_LEGAL_FORM (CS_PROVIDER_CODE, CS_DESCRIPTION, IMX_LEGAL_FORM) values (	62	,'Co-operative society excluded liability (Coöperatie U.A.) according to the regulations of the structural Co-operative society',	'NV');
insert into LOV_CS_LEGAL_FORM (CS_PROVIDER_CODE, CS_DESCRIPTION, IMX_LEGAL_FORM) values (	63	,'Co-operative society with legal liabilty (Coöperatie W.A.) with ordinary structure',	'NV');
insert into LOV_CS_LEGAL_FORM (CS_PROVIDER_CODE, CS_DESCRIPTION, IMX_LEGAL_FORM) values (	64	,'Co-operative society with legal liabilty (Coöperatie W.A.) according to the regulations of the structural Co-operative society',	'NV');
insert into LOV_CS_LEGAL_FORM (CS_PROVIDER_CODE, CS_DESCRIPTION, IMX_LEGAL_FORM) values (	65	,'Co-operative society with limited liability (Coöperatie B.A.) with ordinary structure',	'NV');
insert into LOV_CS_LEGAL_FORM (CS_PROVIDER_CODE, CS_DESCRIPTION, IMX_LEGAL_FORM) values (	66	,'Co-operative society with limited liability (Coöperatie B.A.) according to the regulations of the structural Co-operative society',	'NV');
insert into LOV_CS_LEGAL_FORM (CS_PROVIDER_CODE, CS_DESCRIPTION, IMX_LEGAL_FORM) values (	70	,'Association of owners',	'NV');
insert into LOV_CS_LEGAL_FORM (CS_PROVIDER_CODE, CS_DESCRIPTION, IMX_LEGAL_FORM) values (	71	,'Association (Vereniging) with complete jurisdiction',	'NV');
insert into LOV_CS_LEGAL_FORM (CS_PROVIDER_CODE, CS_DESCRIPTION, IMX_LEGAL_FORM) values (	72	,'Association (Vereniging) with limited jurisdiction',	'NV');
insert into LOV_CS_LEGAL_FORM (CS_PROVIDER_CODE, CS_DESCRIPTION, IMX_LEGAL_FORM) values (	73	,'Religious community (Kerkgenootschap)',	'NV');
insert into LOV_CS_LEGAL_FORM (CS_PROVIDER_CODE, CS_DESCRIPTION, IMX_LEGAL_FORM) values (	74	,'Foundation (Stichting)',	'ST');
insert into LOV_CS_LEGAL_FORM (CS_PROVIDER_CODE, CS_DESCRIPTION, IMX_LEGAL_FORM) values (	81	,'Mutual quarantee association excluded liability (Onderlinge Waarborgmaatschappij U.A.) with ordinary structure',	'ST');
insert into LOV_CS_LEGAL_FORM (CS_PROVIDER_CODE, CS_DESCRIPTION, IMX_LEGAL_FORM) values (	82	,'Mutual quarantee association excluded liability (Onderlinge Waarborgmaatschappij U.A.) according to the regulations of the structural mutual quarantee association',	'ST');
insert into LOV_CS_LEGAL_FORM (CS_PROVIDER_CODE, CS_DESCRIPTION, IMX_LEGAL_FORM) values (	83	,'Mutual quarantee association with legal liabilty (Onderlinge Waarborgmaatschappij W.A.) with ordinary structure',	'ST');
insert into LOV_CS_LEGAL_FORM (CS_PROVIDER_CODE, CS_DESCRIPTION, IMX_LEGAL_FORM) values (	84	,'Mutual quarantee association with legal liabilty (Onderlinge Waarborgmaatschappij W.A.) according to the regulations of the structural mutual quarantee association',	'ST');
insert into LOV_CS_LEGAL_FORM (CS_PROVIDER_CODE, CS_DESCRIPTION, IMX_LEGAL_FORM) values (	85	,'Mutual quarantee association with limited liabilty (Onderlinge Waarborgmaatschappij B.A.) with ordinary structure',	'ST');
insert into LOV_CS_LEGAL_FORM (CS_PROVIDER_CODE, CS_DESCRIPTION, IMX_LEGAL_FORM) values (	86	,'Mutual quarantee association with limited liabilty (Onderlinge Waarborgmaatschappij B.A.) according to the regulations of the structural mutual quarantee association',	'ST');
insert into LOV_CS_LEGAL_FORM (CS_PROVIDER_CODE, CS_DESCRIPTION, IMX_LEGAL_FORM) values (	88	,'Public corporation',	'ST');
insert into LOV_CS_LEGAL_FORM (CS_PROVIDER_CODE, CS_DESCRIPTION, IMX_LEGAL_FORM) values (	89	,'Private corporation',	'ST');
insert into LOV_CS_LEGAL_FORM (CS_PROVIDER_CODE, CS_DESCRIPTION, IMX_LEGAL_FORM) values (	91	,'Foreign legal form with headquarters in the Netherlands',	'ST');
insert into LOV_CS_LEGAL_FORM (CS_PROVIDER_CODE, CS_DESCRIPTION, IMX_LEGAL_FORM) values (	92	,'Secondary with headquarters in foreign country',	'ST');
insert into LOV_CS_LEGAL_FORM (CS_PROVIDER_CODE, CS_DESCRIPTION, IMX_LEGAL_FORM) values (	93	,'European Economical Cooperation (Europees Economisch Samenwerkingsverband)',	'ST');
insert into LOV_CS_LEGAL_FORM (CS_PROVIDER_CODE, CS_DESCRIPTION, IMX_LEGAL_FORM) values (	94	,'Foreign company of the European Community with establishment in the Netherlands',	'ST');
insert into LOV_CS_LEGAL_FORM (CS_PROVIDER_CODE, CS_DESCRIPTION, IMX_LEGAL_FORM) values (	95	,'Foreign company of the European Community with head-office in the Netherlands',	'ST');
insert into LOV_CS_LEGAL_FORM (CS_PROVIDER_CODE, CS_DESCRIPTION, IMX_LEGAL_FORM) values (	96	,'Foreign company resembling at a company of the European Community with establishment in the Netherlands',	'ST');
insert into LOV_CS_LEGAL_FORM (CS_PROVIDER_CODE, CS_DESCRIPTION, IMX_LEGAL_FORM) values (	97	,'Foreign company resembling at a company of the European Community with head-office in the Netherlands',	'ST');
insert into LOV_CS_LEGAL_FORM (CS_PROVIDER_CODE, CS_DESCRIPTION, IMX_LEGAL_FORM) values (	99	,'Other legal forms',	'INC');
commit;